<template>
    <div class="flex justify-between mt-2 mb-2 container mx-auto px-4 py-6">
      <Link class="btn-normal" :href="route('dashboard.index')">Dashboard</Link>
      <Link class="btn-normal" :href="route('my-interview.index')">Back</Link>
    </div>
  
    <h3 class="flex justify-center items-center text-purple-600 font-medium text-3xl">Score</h3>
    <div class="flex justify-center items-center mt-8">
      <svg class="w-40 h-40" viewBox="0 0 36 36">
        <!-- Background circle -->
        <path
          class="text-gray-200"
          stroke-width="3.8"
          stroke="currentColor"
          fill="none"
          d="M18 2.0845
             a 15.9155 15.9155 0 0 1 0 31.831
             a 15.9155 15.9155 0 0 1 0 -31.831"
        />
        <!-- Progress circle -->
        <path
          class="text-purple-600"
          stroke-width="3.8"
          :stroke-dasharray="dashArray"
          stroke="currentColor"
          fill="none"
          stroke-linecap="round"
          d="M18 2.0845
             a 15.9155 15.9155 0 0 1 0 31.831
             a 15.9155 15.9155 0 0 1 0 -31.831"
        />
        <!-- Text in the center -->
        <text x="18" y="22" class="text-xs fill-purple-700 font-bold text-center" text-anchor="middle">
          {{ interview.score }}%
        </text>
      </svg>
    </div>
  
    <section class="container mx-auto mt-8">
      <div class="grid grid-cols-2 gap-4">
  
        <!-- Interview Questions -->
        <Box class="p-4">
          <h4 class="text-purple-500 font-medium text-lg text-center">Interview Questions</h4>
          <div class="whitespace-pre-line mt-2">{{ cleanedQuestions }}</div>
        </Box>
  
        <!-- Your Answers -->
        <Box class="p-4">
          <h4 class="text-purple-500 font-medium text-lg text-center">Your Answers</h4>
          <div class="whitespace-pre-line mt-2">{{ cleanedAnswers }}</div>
        </Box>
  
        <!-- Ideal Answers -->
        <Box class="p-4 col-span-2">
          <h4 class="text-purple-500 font-medium text-lg text-center">Ideal Answers generated by AI</h4>
          <div class="whitespace-pre-line mt-2">{{ cleanedIdealAnswers }}</div>
        </Box>
  
      </div>
    </section>
  </template>
  
  <script setup lang="ts">
  import { computed } from 'vue'
  
  const props = defineProps({
    interview: {
      type: Object,
      required: true
    }
  })
  
  // Score circle
  const dashArray = computed(() => {
    const score = Number(props.interview.score) || 0
    const percent = Math.min(Math.max(score, 0), 100)
    return `${percent}, 100`
  })
  
  // Regex helper to clean JSON string arrays
  function cleanJsonArray(raw: unknown) {
    return String(raw)
      .replace(/^\[\s*/,'')            // remove opening [
      .replace(/\s*\]$/,'')            // remove closing ]
      .replace(/"\s*,\s*"/g, '\n')     // replace "," between items with newline
      .replace(/^"|"$/g,'')            // remove remaining quotes
  }
  
  // Computed properties for all three arrays
  const cleanedQuestions = computed(() => cleanJsonArray(props.interview.questions))
  const cleanedAnswers   = computed(() => cleanJsonArray(props.interview.answer))
  const cleanedIdealAnswers = computed(() => cleanJsonArray(props.interview.ideal_answer))
  </script>
  
  <script lang="ts">
  import MainLayout from '@/components/MainLayout.vue';
  import { Link } from '@inertiajs/vue3';
  import Box from '@/components/Box.vue';
  
  export default {
    layout: MainLayout
  }
  </script>
  